"""Gig table creation

Revision ID: 1fd5a44b61af
Revises: 24b9f9b7a210
Create Date: 2026-07-13 18:06:11.312322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1fd5a44b61af'
down_revision: Union[str, Sequence[str], None] = '24b9f9b7a210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gig',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.profile_id'], ),
    sa.PrimaryKeyConstraint('gig_id')
    )
    op.create_index(op.f('ix_gig_profile_id'), 'gig', ['profile_id'], unique=False)
    op.create_table('gig_skill_link',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gig.gig_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.PrimaryKeyConstraint('gig_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gig_skill_link')
    op.drop_index(op.f('ix_gig_profile_id'), table_name='gig')
    op.drop_table('gig')
    # ### end Alembic commands ###
