"""added banner_url

Revision ID: 4e5fe6dc2939
Revises: 617fd04a769d
Create Date: 2026-08-01 16:18:08.610220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e5fe6dc2939'
down_revision: Union[str, Sequence[str], None] = '617fd04a769d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'banner_url')
    # ### end Alembic commands ###
