"""create initial tables

Revision ID: 5a6bfac40768
Revises: 
Create Date: 2026-06-29 22:07:46.190921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a6bfac40768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=True),
    sa.Column('account_status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='accountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_account_clerk_id'), 'user_account', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_table('student_profile',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('university_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('major_field_of_study', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_student_profile_user_id'), 'student_profile', ['user_id'], unique=True)
    op.create_table('user_review',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewee_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewee_id'], ['user_account.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_user_review_reviewee_id'), 'user_review', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_user_review_reviewer_id'), 'user_review', ['reviewer_id'], unique=False)
    op.create_table('user_skill',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hourly_rate_token_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_user_skill_user_id'), 'user_skill', ['user_id'], unique=False)
    op.create_table('user_wallet',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('available_tokens', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tokens_escrowed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_services_provided', sa.Integer(), nullable=False),
    sa.Column('total_services_received', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_index(op.f('ix_user_wallet_user_id'), 'user_wallet', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wallet_user_id'), table_name='user_wallet')
    op.drop_table('user_wallet')
    op.drop_index(op.f('ix_user_skill_user_id'), table_name='user_skill')
    op.drop_table('user_skill')
    op.drop_index(op.f('ix_user_review_reviewer_id'), table_name='user_review')
    op.drop_index(op.f('ix_user_review_reviewee_id'), table_name='user_review')
    op.drop_table('user_review')
    op.drop_index(op.f('ix_student_profile_user_id'), table_name='student_profile')
    op.drop_table('student_profile')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_clerk_id'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
