"""added turnaround to gigs and uni to userprofile

Revision ID: 9d58e41baab8
Revises: 0f3b5d08dbd2
Create Date: 2026-07-28 23:02:42.562867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9d58e41baab8'
down_revision: Union[str, Sequence[str], None] = '0f3b5d08dbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.add_column('gig', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.add_column('gig', sa.Column('turnaround_time', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # The approval status enum is already handled by the earlier approval-status migration.
    # Re-typing it here is not safe for PostgreSQL and can fail when the target enum does not exist.
    op.create_index(op.f('ix_gig_category_id'), 'gig', ['category_id'], unique=False)
    op.create_foreign_key(None, 'gig', 'category', ['category_id'], ['category_id'])
    op.add_column('user_profile', sa.Column('university', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'university')
    op.drop_constraint(None, 'gig', type_='foreignkey')
    op.drop_index(op.f('ix_gig_category_id'), table_name='gig')
    op.drop_column('gig', 'turnaround_time')
    op.drop_column('gig', 'category_id')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
