"""add gig approval status and admin flag

Revision ID: a7d1016777f5
Revises: 353fdd77e34c
Create Date: 2026-07-23 19:50:25.929948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7d1016777f5'
down_revision: Union[str, Sequence[str], None] = '353fdd77e34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gig', 'approval_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='gig_approval_status'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='gigapprovalstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::gig_approval_status"))
    op.alter_column('gig', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gig', 'reviewed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('gig', 'approval_status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='gigapprovalstatus'),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='gig_approval_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::gig_approval_status"))
    # ### end Alembic commands ###
