"""removed optional on cat and turnaround

Revision ID: b78cd923860d
Revises: 4e5fe6dc2939
Create Date: 2026-08-03 19:16:48.152336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b78cd923860d'
down_revision: Union[str, Sequence[str], None] = '4e5fe6dc2939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop foreign key dependencies before dropping the 'category' table
    op.drop_constraint('gig_category_id_fkey', 'gig', type_='foreignkey')
    op.drop_index(op.f('ix_gig_category_id'), table_name='gig')
    op.drop_column('gig', 'category_id')

    # 2. Create messaging tables
    op.create_table('conversation',
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('user_a_id', sa.Uuid(), nullable=False),
        sa.Column('user_b_id', sa.Uuid(), nullable=False),
        sa.Column('gig_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.Column('user_a_last_read_at', sa.DateTime(), nullable=True),
        sa.Column('user_b_last_read_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['gig_id'], ['gig.gig_id'], ),
        sa.ForeignKeyConstraint(['user_a_id'], ['user_account.user_id'], ),
        sa.ForeignKeyConstraint(['user_b_id'], ['user_account.user_id'], ),
        sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_gig_id'), 'conversation', ['gig_id'], unique=False)
    op.create_index(op.f('ix_conversation_last_message_at'), 'conversation', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversation_user_a_id'), 'conversation', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_conversation_user_b_id'), 'conversation', ['user_b_id'], unique=False)

    op.create_table('message',
        sa.Column('message_id', sa.Uuid(), nullable=False),
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('sender_id', sa.Uuid(), nullable=False),
        sa.Column('body', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
        sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column('attachment_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['user_account.user_id'], ),
        sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)

    # 3. Drop legacy category table
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')

    # 4. Add category_name with temporary server_default to handle existing rows
    op.add_column(
        'gig', 
        sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='General')
    )
    # Remove server default so future models enforce field requirements at application level
    op.alter_column('gig', 'category_name', server_default=None)

    # 5. Backfill any existing NULL values in turnaround_time before setting NOT NULL
    op.execute("UPDATE gig SET turnaround_time = '24 hours' WHERE turnaround_time IS NULL")
    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # 6. Drop unused columns
    op.drop_column('gig', 'banner_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('banner_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gig', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    
    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('gig', 'category_name')
    
    op.create_table('category',
        sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('category_id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    
    op.create_foreign_key(op.f('gig_category_id_fkey'), 'gig', 'category', ['category_id'], ['category_id'])
    op.create_index(op.f('ix_gig_category_id'), 'gig', ['category_id'], unique=False)

    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')

    op.drop_index(op.f('ix_conversation_user_b_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_user_a_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_last_message_at'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_gig_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###