"""gig table modified

Revision ID: c02745db007b
Revises: e1893efe3f96
Create Date: 2026-07-17 16:00:49.853333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c02745db007b'
down_revision: Union[str, Sequence[str], None] = 'e1893efe3f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_gig_profile_id'), table_name='gig')
    op.create_index(op.f('ix_gig_user_id'), 'gig', ['user_id'], unique=False)
    op.drop_constraint(op.f('gig_profile_id_fkey'), 'gig', type_='foreignkey')
    op.create_foreign_key(None, 'gig', 'user_account', ['user_id'], ['user_id'])
    op.drop_column('gig', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'gig', type_='foreignkey')
    op.create_foreign_key(op.f('gig_profile_id_fkey'), 'gig', 'user_profile', ['profile_id'], ['profile_id'])
    op.drop_index(op.f('ix_gig_user_id'), table_name='gig')
    op.create_index(op.f('ix_gig_profile_id'), 'gig', ['profile_id'], unique=False)
    op.drop_column('gig', 'user_id')
    # ### end Alembic commands ###
