"""allans changes

Revision ID: c27beffa2c35
Revises: e242c23bb3d4
Create Date: 2026-08-04 00:48:32.260303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c27beffa2c35'
down_revision: Union[str, Sequence[str], None] = 'e242c23bb3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    # Drop the FK if it exists to avoid errors when constraint is already absent
    op.execute("ALTER TABLE gig DROP CONSTRAINT IF EXISTS gig_category_id_fkey")
    op.drop_table('category')
    op.drop_constraint(op.f('uq_conversation_participants'), 'conversation', type_='unique')
    op.add_column('gig', sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_gig_category_id'), table_name='gig')
    op.create_index(op.f('ix_gig_category_name'), 'gig', ['category_name'], unique=False)
    # Drop the FK if it exists to avoid errors when constraint is already absent
    op.execute("ALTER TABLE gig DROP CONSTRAINT IF EXISTS gig_category_id_fkey")
    op.drop_column('gig', 'category_id')
    op.drop_index(op.f('ix_message_conversation_id_created_at'), table_name='message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_conversation_id_created_at'), 'message', ['conversation_id', 'created_at'], unique=False)
    op.add_column('gig', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gig_category_id_fkey'), 'gig', 'category', ['category_id'], ['category_id'])
    op.drop_index(op.f('ix_gig_category_name'), table_name='gig')
    op.create_index(op.f('ix_gig_category_id'), 'gig', ['category_id'], unique=False)
    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('gig', 'category_name')
    op.create_unique_constraint(op.f('uq_conversation_participants'), 'conversation', ['user_a_id', 'user_b_id'], postgresql_nulls_not_distinct=False)
    op.create_table('category',
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    # ### end Alembic commands ###
