"""allans changes

Revision ID: c27beffa2c35
Revises: e242c23bb3d4
Create Date: 2026-08-04 00:48:32.260303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c27beffa2c35'
down_revision: Union[str, Sequence[str], None] = 'e242c23bb3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema safely using conditional drops."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Safely drop category index and table
    op.drop_index(op.f('ix_category_name'), table_name='category', if_exists=True)
    op.execute("ALTER TABLE gig DROP CONSTRAINT IF EXISTS gig_category_id_fkey")
    op.drop_table('category', if_exists=True)

    # 2. Safely drop conversation constraint
    op.drop_constraint(op.f('uq_conversation_participants'), 'conversation', type_='unique', if_exists=True)

    # 3. Add category_name column to gig if it doesn't already exist
    # Using raw SQL check to prevent "column already exists" crash on re-runs
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name='gig' AND column_name='category_name'
            ) THEN 
                ALTER TABLE gig ADD COLUMN category_name VARCHAR NOT NULL; 
            END IF; 
        END $$;
    """)

    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # 4. Safely drop old index, create new index on gig
    op.drop_index(op.f('ix_gig_category_id'), table_name='gig', if_exists=True)
    
    # Create index if it doesn't already exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_gig_category_name ON gig (category_name)")

    # 5. Drop category_id column safely
    op.drop_column('gig', 'category_id', if_exists=True)

    # 6. Safely drop message index
    op.drop_index(op.f('ix_message_conversation_id_created_at'), table_name='message', if_exists=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_conversation_id_created_at'), 'message', ['conversation_id', 'created_at'], unique=False)
    op.add_column('gig', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('gig_category_id_fkey'), 'gig', 'category', ['category_id'], ['category_id'])
    op.drop_index(op.f('ix_gig_category_name'), table_name='gig', if_exists=True)
    op.create_index(op.f('ix_gig_category_id'), 'gig', ['category_id'], unique=False)
    op.alter_column('gig', 'turnaround_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('gig', 'category_name', if_exists=True)
    op.create_unique_constraint(op.f('uq_conversation_participants'), 'conversation', ['user_a_id', 'user_b_id'], postgresql_nulls_not_distinct=False)
    op.create_table('category',
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name=op.f('category_pkey'))
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    # ### end Alembic commands ###