"""student verification added

Revision ID: caa005e812d5
Revises: c27beffa2c35
Create Date: 2026-08-04 14:05:46.704763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'caa005e812d5'
down_revision: Union[str, Sequence[str], None] = 'c27beffa2c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='verificationstatus'), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('school_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_send_attempts', sa.Integer(), nullable=False),
    sa.Column('last_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.clerk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_verification_created_at'), 'student_verification', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_verification_user_id'), 'student_verification', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_verification_user_id'), table_name='student_verification')
    op.drop_index(op.f('ix_student_verification_created_at'), table_name='student_verification')
    op.drop_table('student_verification')
    # ### end Alembic commands ###
