"""Srialization of tag_id

Revision ID: e1893efe3f96
Revises: 055a95483f11
Create Date: 2026-07-17 11:06:05.760737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1893efe3f96'
down_revision: Union[str, Sequence[str], None] = '055a95483f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('gig_tag_link',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gig.gig_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('gig_id', 'tag_id')
    )
    op.drop_table('gig_skill_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gig_skill_link',
    sa.Column('gig_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gig.gig_id'], name=op.f('gig_skill_link_gig_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], name=op.f('gig_skill_link_skill_id_fkey')),
    sa.PrimaryKeyConstraint('gig_id', 'skill_id', name=op.f('gig_skill_link_pkey'))
    )
    op.drop_table('gig_tag_link')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
