"""user account table redone

Revision ID: e42f6e3a6c1c
Revises: f6ea5fce7c12
Create Date: 2026-06-30 18:44:33.785173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e42f6e3a6c1c'
down_revision: Union[str, Sequence[str], None] = 'f6ea5fce7c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_account', 'is_email_verified')
    op.drop_column('user_account', 'last_login')
    op.drop_column('user_account', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_account', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_account', sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('user_account', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
